version = 0.1
default-task = 'dev'

[[task]]
name = 'setup'
targets = ['k3d.config.yml']
run = '''
  k3d cluster create -c k3d.config.yml
  ark install istio
  kubectl label namespace default istio-injection=enabled
'''

[[task]]
name = 'nuke'
run = '''
  k3d cluster delete -c k3d.config.yml
'''

[[task]]
name = 'dev'
deps = ['setup']
run = 'skaffold dev --default-repo registry.localhost:5000'

[[task]]
name = 'list'
args = ['DIRECTORY']
echo = true
run = '''
  ls ${{ DIRECTORY }}
'''
