apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: umbrella
servers: 1
agents: 2
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
    proxy:
      remoteURL: https://registry-1.docker.io
      username: ""
      password: ""
    volumes:
      - /mnt/k3d-registry
options:
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*

