apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: external
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
  - "*"
  gateways:
  - external
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "app.fullname" . }}
        port:
          number: {{ .Values.service.port }}
